# TypeProf 0.21.11

# Classes
module Baykit
  module BayServer
    module Agent
      module Multiplexer
        class TaxiMultiplexer
          include Baykit::BayServer
          include Multiplexer

          def initialize: (GrandAgent agt) -> void
          def to_s: -> String
          def req_accept: (Rudders::Rudder rd) -> void
          def req_connect: (Rudders::Rudder rd, Addrinfo adr) -> void
          def req_read: (Rudders::Rudder rd) -> void
          def req_write: (Rudders::Rudder rd, String buf, Addrinfo adr, Object tag) { () -> void } -> void
          def req_close: (Rudders::Rudder rd) -> void
          def is_non_blocking: -> bool
          def use_async_api: -> bool
          def cancel_read: (Common::RudderState st) -> void
          def cancel_write: (Common::RudderState st) -> void
          def next_accept: (Common::RudderState st) -> void
          def next_read: (Rudders::Rudder rd) -> void
          def next_write: (Rudders::Rudder rd) -> void
          def next_run: (Common::RudderState st, bool for_read) -> void
          def do_next_read: (Rudders::Rudder rd) -> void
          def do_next_write: (Rudders::Rudder rd) -> void

          class TaxiForMpx
            @rudder_state: Common::RudderState
            @for_read: bool

            def initialize: (Common::RudderState st, bool for_read) -> void
            def depart: -> void
            def on_timer: -> void
          end
        end
      end
    end
  end
end
