# TypeProf 0.21.11

# Classes
module Baykit
  module BayServer
    module Bcf
      class ParseException
        def initialize: (untyped file_name, untyped line_no, untyped msg) -> void
      end
    end
  end
end
