# Classes
module Baykit
  module BayServer
    module Protocol
      class CommandPacker
        include Baykit::BayServer::Util::Reusable

        @pkt_packer: PacketPacker
        @pkt_store: PacketStore

        attr_reader pkt_packer: PacketPacker
        attr_reader pkt_store: PacketStore

        def initialize: (PacketPacker pkt_packer, PacketStore store) -> void
        def reset: -> void
        def post: (Ships::Ship sip, Command cmd, bool flush) ?{ (?bool) -> void } -> bool
      end
    end
  end
end
