# Classes
module Baykit
  module BayServer
    module Protocol
      class Packet
        include Baykit::BayServer::Util::Reusable

        INITIAL_BUF_SIZE: Integer

        @type: Integer
        @header_len: Integer
        @max_data_len: Integer
        @buf: String
        @buf_len: Integer
        @header_accessor: PacketPartAccessor
        @data_accessor: PacketPartAccessor

        attr_reader type: Integer
        attr_reader buf: String
        attr_accessor buf_len: Integer
        attr_reader header_len: Integer
        attr_reader max_data_len: Integer
        attr_reader header_accessor: PacketPartAccessor
        attr_reader data_accessor: PacketPartAccessor

        def initialize: (Integer `type`, Integer header_len, Integer max_data_len) -> void
        def reset: -> void
        def data_len: -> Integer
        def expand: -> void
        def to_s: -> String
      end
    end
  end
end
