# TypeProf 0.21.11

# Classes
module Baykit
  module BayServer
    module Protocol
      class PacketPacker
        def reset: () -> void
        def post: (Ships::Ship sip, Packet pkt) -> void
      end
    end
  end
end
