# Classes
module Baykit
  module BayServer
    module Protocol
      class PacketPacker
        include Baykit::BayServer::Util::Reusable

        def reset: -> void
        def post: (Ships::Ship sip, Packet pkt, bool flush) { (?bool) -> void } -> bool
      end
    end
  end
end
