# TypeProf 0.21.11

# Classes
module Baykit
  module BayServer
    module Protocol
      class ProtocolException < StandardError
        def initialize: (?String fmt, *untyped args) -> void
      end
    end
  end
end
