# TypeProf 0.21.11

# Classes
module Baykit
  module BayServer
    module Docker
      module Cgi
        class CgiReqContentHandler
          READ_CHUNK_SIZE: Integer
          @cgi_docker: CgiDocker
          @tour: Tours::Tour
          @tour_id: Integer
          @std_out_closed: bool
          @std_err_closed: bool
          @std_in_rd: Rudders::Rudder
          @last_access: Integer
          @pid: Integer
          @available: false
          @std_out_rd: Rudders::Rudder
          @std_err_rd: Rudders::Rudder
          @env: Hash[String, String]

          attr_accessor multiplexer: Common::Multiplexer
          def initialize: (CgiDocker cgi_docker, Tours::Tour tur, Hash[String, String] env) -> void
          def on_read_req_content: (Tours::Tour tur, String buf, Integer start, Integer len) -> void
          def on_end_req_content: (Tours::Tour tur) -> void
          def on_abort_req: (Tours::Tour tur) -> bool
          def req_start_tour: -> void
          def std_out_closed: -> bool
          def std_err_closed: -> bool
          def access: -> void
          def timed_out: -> bool
          def process_finished: -> void
          def run: -> void
        end
      end
    end
  end
end
