# Classes
module Baykit
  module BayServer
    module Agent
      class GrandAgent
        SELECT_TIMEOUT_SEC: Integer
        CMD_OK: Integer
        CMD_CLOSE: Integer
        CMD_RELOAD_CERT: Integer
        CMD_MEM_USAGE: Integer
        CMD_SHUTDOWN: Integer
        CMD_ABORT: Integer
        CMD_CATCHUP: Integer

        self.@agent_count: Integer
        self.@max_agent_id: Integer
        self.@max_ships: Integer
        self.@agents: Array[GrandAgent]
        self.@listeners: Array[LifecycleListener]
        self.@finale: bool

        @agent_id: Integer
        @max_inbound_ships: Integer
        @anchorable: bool
        @job_multiplexer: Common::Multiplexer
        @spider_multiplexer: Common::Multiplexer
        @taxi_multiplexer: Multiplexer::TaxiMultiplexer
        @timer_handlers: Array[TimerHandler]
        @select_timeout_sec: Integer
        @aborted: bool
        @letter_queue: Array[Letters::Letter]
        @letter_queue_lock: Thread::Mutex
        @postpone_queue: Array[Common::Postpone]
        @postpone_queue_lock: Thread::Mutex
        @accepted_letter_store: Util::ObjectStore
        @connected_letter_store: Util::ObjectStore
        @read_letter_store: Util::ObjectStore
        @wrote_letter_store: Util::ObjectStore
        @closed_letter_store: Util::ObjectStore
        @error_letter_store: Util::ObjectStore
        @command_receiver: CommandReceiver
        @net_multiplexer: Common::Multiplexer
        @spin_multiplexer: Common::Multiplexer
        @file_multiplexer: Common::Multiplexer
        @recipient: Common::Recipient
        @last_timeout_check: Integer
        @busy: bool

        attr_reader agent_id: Integer
        attr_reader anchorable: bool
        attr_reader net_multiplexer: Common::Multiplexer
        attr_reader job_multiplexer: Common::Multiplexer
        attr_reader taxi_multiplexer: Multiplexer::TaxiMultiplexer
        attr_reader spin_multiplexer: Common::Multiplexer
        attr_reader spider_multiplexer: Common::Multiplexer
        attr_reader file_multiplexer: Common::Multiplexer
        attr_reader recipient: Common::Recipient
        attr_reader max_inbound_ships: Integer
        attr_reader aborted: bool
        attr_reader command_receiver: CommandReceiver
        attr_reader timer_handlers: Array[TimerHandler]
        attr_reader last_timeout_check: Integer
        attr_reader letter_queue: Array[Letters::Letter]
        attr_reader letter_queue_lock: Thread::Mutex
        attr_reader postpone_queue: Array[Common::Postpone]
        attr_reader postpone_queue_lock: Thread::Mutex

        def initialize: (Integer agent_id, Integer max_ships, bool anchorable) -> void
        def to_s: -> String
        def inspect: -> String
        def start: -> Thread
        def run: -> void
        def abort_agent: -> void
        def req_shutdown: -> void
        def print_usage: -> void
        def add_timer_handler: (TimerHandler handler) -> void
        def remove_timer_handler: (TimerHandler handler) -> void
        def add_command_receiver: (Rudders::Rudder rd) -> void
        def send_accepted_letter: (Rudders::Rudder rd, Common::Multiplexer mpx, Rudders::Rudder client_rd, bool wakeup) -> void
        def send_connected_letter: (Rudders::Rudder rd, Common::Multiplexer mpx, bool wakeup) -> void
        def send_read_letter: (Rudders::Rudder rd, Common::Multiplexer mpx, Integer n, untyped adr, bool wakeup) -> void
        def send_wrote_letter: (Rudders::Rudder rd, Common::Multiplexer mpx, Integer n, bool wakeup) -> void
        def send_closed_letter: (Rudders::Rudder rd, Common::Multiplexer mpx, bool wakeup) -> void
        def send_error_letter: (Rudders::Rudder rd, Common::Multiplexer mpx, Exception err, bool wakeup) -> void
        def return_letter: (Letters::Letter let) -> void
        def shutdown: -> void
        def abort: -> void
        def reload_cert: -> void
        def add_postpone: (Common::Postpone p) -> void
        def req_catch_up: -> void
        def catch_up: -> void

        private
        def ring: -> void
        def send_letter: (Letters::Letter let, bool wakeup) -> void
        def on_accepted: (Letters::AcceptedLetter let, Common::RudderState st) -> void
        def on_connected: (Letters::ConnectedLetter let, Common::RudderState st) -> void
        def on_read: (Letters::ReadLetter let, Common::RudderState st) -> void
        def on_wrote: (Letters::WroteLetter let, Common::RudderState st) -> void
        def on_closed: (Letters::ClosedLetter let, Common::RudderState st) -> void
        def on_error: (Letters::ErrorLetter let, Common::RudderState st) -> void
        def next_action: (Common::RudderState st, Integer act, bool reading) -> void
        def count_postpone: -> Integer

        def self.init: (Array[Integer] agt_ids, Integer max_ships) -> void
        def self.get: (Integer agt_id) -> GrandAgent
        def self.add: (Integer agt_id, bool anchorable) -> GrandAgent
        def self.add_lifecycle_listener: (LifecycleListener lis) -> void
      end
    end
  end
end
