# TypeProf 0.21.11

# Classes
module Baykit
  module BayServer
    module Agent
      class Letter
        ACCEPTED: Integer
        CONNECTED: Integer
        READ: Integer
        WROTE: Integer
        CLOSEREQ: Integer
        @type: Integer
        @state: Multiplexer::RudderState
        @client_rudder: Rudders::Rudder
        @address: Addrinfo
        @n_bytes: Integer
        @err: Exception

        def initialize: (Integer `type`, Multiplexer::RudderState st, Rudders::Rudder client_rd, Integer n, Addrinfo adr, Exception err) -> void
      end
    end
  end
end
