# TypeProf 0.21.11

# Classes
module Baykit
  module BayServer
    module Rudders
      class IORudder
        include Rudder

        @io: IO
        @non_blocking: false

        def initialize: (IO io) -> void
        def key: -> Object
        def set_non_blocking: -> void
        def read: (String buf, Integer len) -> Integer
        def write: (String buf) -> Integer
        def close: -> void
        def io: -> IO
      end
    end
  end
end
