# TypeProf 0.21.11

# Classes
module Baykit
  module BayServer
    module Taxi
      class Taxi
        self.@taxi_id_counter: Util::Counter
        @taxi_id: Integer

        def initialize: -> void
        def to_s: -> String
        def run: -> void
        def depart: -> void
      end
    end
  end
end
