# TypeProf 0.21.11

# Classes
module Baykit
  module BayServer
    module Docker
      module SendFile
        class FileContentHandler
          @tour: Tours::Tour
          @path: String
          @charset: String
          @mime_type: String
          @abortable: bool
          @store: FileStore
          @file_content: FileContent
          @lock: Mutex

          def initialize: (Tours::Tour tur, FileStore store, String path, String charset) -> void
          def on_read_content: (Tours::Tour tur, String buf, Integer start, Integer len) -> void
          def on_end_req_content: (Tours::Tour tur) -> void
          def on_abort_req: (Tours::Tour tur) -> bool
          def req_start_tour: -> void
          def send_file_async: -> void
          def send_file_from_cache: -> void
        end
      end
    end
  end
end
