# TypeProf 0.21.11

# Classes
module Baykit
  module BayServer
    module Agent
      module Letters
        class ClosedLetter
          def initialize: (Multiplexer::RudderState st) -> void
        end
      end
    end
  end
end
