# TypeProf 0.21.3

# Classes
module Baykit
  module BayServer
    module Agent
      module Letters
        class Letter
          @state_id: Integer
          @rudder: Rudders::Rudder
          @multiplexer: Common::Multiplexer

          def initialize: (Integer state_id, Rudders::Rudder rd, Common::Multiplexer mpx) -> void
        end
      end
    end
  end
end
