# Classes
module Baykit
  module BayServer
    module Agent
      module Letters
        class Letter
          include Baykit::BayServer::Util::Reusable

          @rudder: Rudders::Rudder | nil
          @multiplexer: Common::Multiplexer | nil

          attr_accessor rudder: Rudders::Rudder | nil
          attr_accessor multiplexer: Common::Multiplexer | nil

          def initialize: -> void
          def init: (Rudders::Rudder rd, Common::Multiplexer mpx) -> void
          def reset: -> void
        end
      end
    end
  end
end
