# TypeProf 0.21.11

# Classes
module Baykit
  module BayServer
    module Agent
      module Letters
        class ReadLetter
          @n_bytes: Integer
          @address: String

          def initialize: (Integer state_id, Rudders::Rudder rd, Common::Multiplexer mpx, Integer n, ?String adr) -> void
        end
      end
    end
  end
end
