# Classes
module Baykit
  module BayServer
    module Agent
      module Letters
        class ReadLetter < Letter
          @n_bytes: Integer
          @address: untyped  # sender addr (Addrinfo or String)

          attr_accessor n_bytes: Integer
          attr_accessor address: untyped

          def init: (Rudders::Rudder rd, Common::Multiplexer mpx, Integer n, ?untyped adr) -> void
          def reset: -> void
        end
      end
    end
  end
end
