# Classes
module Baykit
  module BayServer
    module Agent
      module Letters
        class WroteLetter < Letter
          @n_bytes: Integer

          attr_accessor n_bytes: Integer

          def init: (Rudders::Rudder rd, Common::Multiplexer mpx, Integer n) -> void
          def reset: -> void
        end
      end
    end
  end
end
