# TypeProf 0.21.11

# Classes
module Baykit
  module BayServer
    module Agent
      module Letters
        class WroteLetter
          @n_bytes: Integer

          def initialize: (Integer state_id, Rudders::Rudder rd, Common::Multiplexer mpx,  Integer n) -> void
        end
      end
    end
  end
end
