# Classes
module Baykit
  module BayServer
    module Docker
      module City
        include Docker

        def name: -> String
        def clubs: -> Array[Club]
        def towns: -> Array[Town]
        def enter: (Tours::Tour tur) -> void
        def get_trouble: -> untyped
        def log: (Tours::Tour tur) -> void
      end
    end
  end
end
