# TypeProf 0.21.11

# Classes
module Baykit
  module BayServer
    module Docker
      module Ajp
        module Command
          class CmdEndResponse
            attr_accessor reuse: bool
            def initialize: -> void
            def unpack: (AjpPacket pkt) -> void
            def pack: (AjpPacket pkt) -> void
            def handle: (AjpCommandHandler handler) -> Integer
          end
        end
      end
    end
  end
end
