# TypeProf 0.21.11

# Classes
module Baykit
  module BayServer
    module Docker
      module Http
        class HtpWarpDocker
          include OpenSSL
          @secure: bool
          @support_h2: bool
          @ssl_ctx: OpenSSL::SSL::SSLContext
          @trace_ssl: bool

          def initialize: -> void
          def init: (Bcf::BcfElement elm, BayServer::Docker parent) -> void
          def init_key_val: (Bcf::BcfKeyVal kv) -> bool
          def secure: -> bool
          def protocol: -> String
          def new_transporter: (Agent::GrandAgent agt, Rudders::Rudder rd, Ships::Ship sip) -> Agent::Multiplexer::PlainTransporter
        end
      end
    end
  end
end
