# Classes
module Baykit
  module BayServer
    module Common
      class InboundShip < Baykit::BayServer::Ships::Ship
        MAX_TOURS: Integer

        self.@err_counter: Util::Counter

        @lock: ::Monitor
        @active_tours: Array[Tours::Tour]
        @protocol_handler: Protocol::ProtocolHandler | nil
        @port_docker: Docker::Port | nil
        @socket_timeout_sec: Integer
        @tour_store: Tours::TourStore
        @need_end: bool

        attr_reader port_docker: Docker::Port | nil
        attr_reader protocol_handler: Protocol::ProtocolHandler | nil
        attr_accessor need_end: bool
        attr_reader socket_timeout_sec: Integer
        attr_reader tour_store: Tours::TourStore
        attr_reader active_tours: Array[Tours::Tour]
        attr_reader lock: ::Monitor

        def self.err_counter: -> Util::Counter

        def initialize: -> void
        def to_s: -> String
        def init_inbound: (Rudders::Rudder rd, Integer agt_id, Common::Transporter tp, Docker::Port port_dkr, Protocol::ProtocolHandler proto_hnd) -> void
        def reset: -> void
        def notify_handshake_done: (String? proto) -> Integer
        def notify_connect: -> void
        def notify_read: (String buf) -> Integer
        def notify_eof: -> Integer
        def notify_error: (Exception e) -> void
        def notify_protocol_error: (Exception e) -> bool
        def notify_close: -> void
        def check_timeout: (Integer duration_sec) -> bool
        def set_protocol_handler: (Protocol::ProtocolHandler proto_handler) -> void
        def get_tour: (Integer tur_key, ?bool force, ?bool rent) -> (Tours::Tour | nil)
        def get_error_tour: -> Tours::Tour
        def send_headers: (Integer check_id, Tours::Tour tur) -> void
        def send_redirect: (Integer check_id, Tours::Tour tur, Integer status, String location) -> void
        def send_res_content: (Integer check_id, Tours::Tour tur, String bytes, Integer ofs, Integer len) ?{ (?bool) -> void } -> bool
        def transfer_res_content: (Integer check_id, Tours::Tour tur, Rudders::Rudder file_rd, Integer ofs, Integer len) ?{ () -> void } -> void
        def send_end_tour: (Integer chk_ship_id, Tours::Tour tur) ?{ (?bool) -> void } -> void
        def send_error: (Integer chk_id, Tours::Tour tour, Integer status, String? message, Exception? e) -> void
        def end_ship: -> void
        def abort_tours: -> void
        def tour_handler: -> untyped
        def return_tour: (Tours::Tour tur) -> void

        private
        def send_error_content: (Integer chk_id, Tours::Tour tour, String content) -> void
        def self.uniq_key: (Integer sip_id, Integer tur_key) -> Integer
      end
    end
  end
end
