# Classes
module Baykit
  module BayServer
    module Common
      class RudderState
        include Baykit::BayServer::Util::Reusable

        self.@id_counter: Util::Counter

        @id: Integer
        @rudder: Rudders::Rudder | nil
        @multiplexer: Common::Multiplexer | nil
        @transporter: Common::Transporter | nil
        @timeout_sec: Integer
        @read_buf: String
        @buf_size: Integer
        @write_queue: Array[WriteUnit]
        @write_queue_lock: Thread::Mutex
        @reading_lock: Thread::Mutex
        @writing_lock: Thread::Mutex
        @last_access_time: Integer
        @write_unit_store: Util::ObjectStore

        attr_reader id: Integer
        attr_reader rudder: Rudders::Rudder | nil
        attr_reader transporter: Common::Transporter | nil
        attr_accessor multiplexer: Common::Multiplexer | nil
        attr_reader last_access_time: Integer
        attr_accessor closing: bool
        attr_reader read_buf: String
        attr_reader buf_size: Integer
        attr_reader write_queue: Array[WriteUnit]
        attr_accessor handshaking: bool
        attr_accessor reading: bool
        attr_accessor writing: bool
        attr_accessor bytes_read: Integer
        attr_accessor bytes_wrote: Integer
        attr_reader write_queue_lock: Thread::Mutex
        attr_reader reading_lock: Thread::Mutex
        attr_reader writing_lock: Thread::Mutex
        attr_accessor finale: bool
        attr_accessor accepting: bool
        attr_accessor connecting: bool
        attr_accessor skip_formalities: bool
        attr_accessor quick_ack: bool

        def self.id_counter: -> Util::Counter

        def initialize: -> void
        def rent_write_unit: -> WriteUnit
        def return_write_unit: (WriteUnit u) -> void
        def init: (Rudders::Rudder rd, ?Common::Transporter? tp, ?Integer timeout_sec) -> void
        def to_s: -> String
        def reset: -> void
        def access: -> void
        def remaining: -> Integer
        def buffer_available?: -> bool
        def end: -> void
      end
    end
  end
end
