# TypeProf 0.21.3

# Classes
module Baykit
  module BayServer
    module Common
      class RudderStateStore
        self.@stores: Hash[untyped, untyped]
        @factory: ^-> untyped

        def initialize: -> void
        def print_usage: (Integer indent) -> void
        def self.init: -> void
        def self.get_store: (Integer agent_id) -> RudderStateStore

        class AgentListener
          def add: (Integer agt_id) -> void
          def remove: (Integer agt_id) -> void
        end
      end
    end
  end
end
