# Classes
module Baykit
  module BayServer
    module Common
      class WriteUnit
        include Baykit::BayServer::Util::Reusable

        @buf: String
        @len: Integer
        @wrote: Integer
        @adr: untyped
        @tag: Object | nil
        @listener: Proc | nil

        attr_reader buf: String
        attr_accessor len: Integer
        attr_accessor wrote: Integer
        attr_reader adr: untyped
        attr_reader tag: Object | nil
        attr_reader listener: Proc | nil

        def initialize: -> void
        def init: (String src, Integer ofs, Integer len, untyped adr, Object? tag) ?{ (?bool) -> void } -> void
        def remaining: -> Integer
        def remaining_buf: -> String
        def done: (?bool buffer_available) -> void
        def reset: -> void
      end
    end
  end
end
