# TypeProf 0.21.11

# Classes
module Baykit
  module BayServer
    module Docker
      module Http
        module H2
          module Command
            class CmdWindowUpdate
              include H2

              attr_accessor window_size_increment: Integer
              def initialize: (Integer stream_id, ?Integer flags) -> void
              def unpack: (H2Packet pkt) -> void
              def pack: (H2Packet pkt) -> void
              def handle: (H2CommandHandler cmd_handler) -> Integer
            end
          end
        end
      end
    end
  end
end
