# TypeProf 0.21.11

# Classes
module Baykit
  module BayServer
    module Docker
      module Http
        module H2
          module Command
            class CmdPing
              include H2
              @opaque_data: String

              def initialize: (Integer stream_id, ?Integer flags, ?String opaque_data) -> void
              def unpack: (H2Packet pkt) -> void
              def pack: (H2Packet pkt) -> void
              def handle: (H2CommandHandler cmd_handler) -> Integer
            end
          end
        end
      end
    end
  end
end
