# Classes
module Baykit
  module BayServer
    module Util
      class MD5Password
        def self.encode: (String password) -> String
        def bytesToString: (Array[Integer] bytes) -> String
      end
    end
  end
end
