# TypeProf 0.21.11

# Classes
module Baykit
  module BayServer
    module Util
      class NioSelector
        @selector: NIO::Selector
        @io_monitor_map: Hash[IO, NIO::Monitor]

        def initialize: -> void
        def select: (?(Integer | nil) timeout_sec) -> Hash[IO, Integer]

        private
        def register_read: (IO ch, Hash[IO, Integer] rd_list) -> void
        def register_write: (IO ch, Hash[IO, Integer] rd_list) -> void
        def unregister_read: (IO ch, Hash[IO, Integer] rd_list) -> void
        def unregister_write: (IO ch, Hash[IO, Integer] rd_list) -> void
      end
    end
  end
end
