# Classes
module Baykit
  module BayServer
    module Util
      class ObjectStore
        include Reusable

        @free_list: Array[Reusable]
        @active_list: Array[Reusable]
        @factory: ObjectFactory | Proc | nil

        attr_reader free_list: Array[Reusable]
        attr_reader active_list: Array[Reusable]
        attr_reader factory: ObjectFactory | Proc | nil

        def initialize: (?(ObjectFactory | Proc | nil) factory) -> void
        def reset: -> void
        def rent: -> Reusable
        def Return: (Reusable obj, ?bool reuse) -> void
        def print_usage: (Integer indent) -> void
      end
    end
  end
end
